// Code generated by protoc-gen-go. DO NOT EDIT.
// source: meeting.proto

package meeting

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Meeting struct {
	Missing              bool               `protobuf:"varint,1,opt,name=missing,proto3" json:"missing,omitempty"`
	Information          string             `protobuf:"bytes,2,opt,name=information,proto3" json:"information,omitempty"`
	Room                 *Meeting_Room      `protobuf:"bytes,3,opt,name=room,proto3" json:"room,omitempty"`
	Current              *Meeting_Trace     `protobuf:"bytes,38,opt,name=current,proto3" json:"current,omitempty"`
	Hosts                []*Meeting_Unknown `protobuf:"bytes,27,rep,name=hosts,proto3" json:"hosts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Meeting) Reset()         { *m = Meeting{} }
func (m *Meeting) String() string { return proto.CompactTextString(m) }
func (*Meeting) ProtoMessage()    {}
func (*Meeting) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c1c38a5767000fe, []int{0}
}

func (m *Meeting) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Meeting.Unmarshal(m, b)
}
func (m *Meeting) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Meeting.Marshal(b, m, deterministic)
}
func (m *Meeting) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Meeting.Merge(m, src)
}
func (m *Meeting) XXX_Size() int {
	return xxx_messageInfo_Meeting.Size(m)
}
func (m *Meeting) XXX_DiscardUnknown() {
	xxx_messageInfo_Meeting.DiscardUnknown(m)
}

var xxx_messageInfo_Meeting proto.InternalMessageInfo

func (m *Meeting) GetMissing() bool {
	if m != nil {
		return m.Missing
	}
	return false
}

func (m *Meeting) GetInformation() string {
	if m != nil {
		return m.Information
	}
	return ""
}

func (m *Meeting) GetRoom() *Meeting_Room {
	if m != nil {
		return m.Room
	}
	return nil
}

func (m *Meeting) GetCurrent() *Meeting_Trace {
	if m != nil {
		return m.Current
	}
	return nil
}

func (m *Meeting) GetHosts() []*Meeting_Unknown {
	if m != nil {
		return m.Hosts
	}
	return nil
}

type Meeting_PhoneNumber struct {
	CountryCode          string   `protobuf:"bytes,1,opt,name=country_code,json=countryCode,proto3" json:"country_code,omitempty"`
	CountryName          string   `protobuf:"bytes,2,opt,name=country_name,json=countryName,proto3" json:"country_name,omitempty"`
	CountryPrefix        string   `protobuf:"bytes,3,opt,name=country_prefix,json=countryPrefix,proto3" json:"country_prefix,omitempty"`
	Number               string   `protobuf:"bytes,4,opt,name=number,proto3" json:"number,omitempty"`
	EasyNumber           string   `protobuf:"bytes,5,opt,name=easy_number,json=easyNumber,proto3" json:"easy_number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Meeting_PhoneNumber) Reset()         { *m = Meeting_PhoneNumber{} }
func (m *Meeting_PhoneNumber) String() string { return proto.CompactTextString(m) }
func (*Meeting_PhoneNumber) ProtoMessage()    {}
func (*Meeting_PhoneNumber) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c1c38a5767000fe, []int{0, 0}
}

func (m *Meeting_PhoneNumber) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Meeting_PhoneNumber.Unmarshal(m, b)
}
func (m *Meeting_PhoneNumber) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Meeting_PhoneNumber.Marshal(b, m, deterministic)
}
func (m *Meeting_PhoneNumber) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Meeting_PhoneNumber.Merge(m, src)
}
func (m *Meeting_PhoneNumber) XXX_Size() int {
	return xxx_messageInfo_Meeting_PhoneNumber.Size(m)
}
func (m *Meeting_PhoneNumber) XXX_DiscardUnknown() {
	xxx_messageInfo_Meeting_PhoneNumber.DiscardUnknown(m)
}

var xxx_messageInfo_Meeting_PhoneNumber proto.InternalMessageInfo

func (m *Meeting_PhoneNumber) GetCountryCode() string {
	if m != nil {
		return m.CountryCode
	}
	return ""
}

func (m *Meeting_PhoneNumber) GetCountryName() string {
	if m != nil {
		return m.CountryName
	}
	return ""
}

func (m *Meeting_PhoneNumber) GetCountryPrefix() string {
	if m != nil {
		return m.CountryPrefix
	}
	return ""
}

func (m *Meeting_PhoneNumber) GetNumber() string {
	if m != nil {
		return m.Number
	}
	return ""
}

func (m *Meeting_PhoneNumber) GetEasyNumber() string {
	if m != nil {
		return m.EasyNumber
	}
	return ""
}

type Meeting_Phones struct {
	Info                 []*Meeting_PhoneNumber `protobuf:"bytes,1,rep,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *Meeting_Phones) Reset()         { *m = Meeting_Phones{} }
func (m *Meeting_Phones) String() string { return proto.CompactTextString(m) }
func (*Meeting_Phones) ProtoMessage()    {}
func (*Meeting_Phones) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c1c38a5767000fe, []int{0, 1}
}

func (m *Meeting_Phones) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Meeting_Phones.Unmarshal(m, b)
}
func (m *Meeting_Phones) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Meeting_Phones.Marshal(b, m, deterministic)
}
func (m *Meeting_Phones) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Meeting_Phones.Merge(m, src)
}
func (m *Meeting_Phones) XXX_Size() int {
	return xxx_messageInfo_Meeting_Phones.Size(m)
}
func (m *Meeting_Phones) XXX_DiscardUnknown() {
	xxx_messageInfo_Meeting_Phones.DiscardUnknown(m)
}

var xxx_messageInfo_Meeting_Phones proto.InternalMessageInfo

func (m *Meeting_Phones) GetInfo() []*Meeting_PhoneNumber {
	if m != nil {
		return m.Info
	}
	return nil
}

type Meeting_Unknown struct {
	Xmpp                 string   `protobuf:"bytes,1,opt,name=xmpp,proto3" json:"xmpp,omitempty"`
	Gw1                  string   `protobuf:"bytes,2,opt,name=gw1,proto3" json:"gw1,omitempty"`
	Gw2                  string   `protobuf:"bytes,3,opt,name=gw2,proto3" json:"gw2,omitempty"`
	File                 string   `protobuf:"bytes,4,opt,name=file,proto3" json:"file,omitempty"`
	Log                  string   `protobuf:"bytes,8,opt,name=log,proto3" json:"log,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Meeting_Unknown) Reset()         { *m = Meeting_Unknown{} }
func (m *Meeting_Unknown) String() string { return proto.CompactTextString(m) }
func (*Meeting_Unknown) ProtoMessage()    {}
func (*Meeting_Unknown) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c1c38a5767000fe, []int{0, 2}
}

func (m *Meeting_Unknown) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Meeting_Unknown.Unmarshal(m, b)
}
func (m *Meeting_Unknown) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Meeting_Unknown.Marshal(b, m, deterministic)
}
func (m *Meeting_Unknown) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Meeting_Unknown.Merge(m, src)
}
func (m *Meeting_Unknown) XXX_Size() int {
	return xxx_messageInfo_Meeting_Unknown.Size(m)
}
func (m *Meeting_Unknown) XXX_DiscardUnknown() {
	xxx_messageInfo_Meeting_Unknown.DiscardUnknown(m)
}

var xxx_messageInfo_Meeting_Unknown proto.InternalMessageInfo

func (m *Meeting_Unknown) GetXmpp() string {
	if m != nil {
		return m.Xmpp
	}
	return ""
}

func (m *Meeting_Unknown) GetGw1() string {
	if m != nil {
		return m.Gw1
	}
	return ""
}

func (m *Meeting_Unknown) GetGw2() string {
	if m != nil {
		return m.Gw2
	}
	return ""
}

func (m *Meeting_Unknown) GetFile() string {
	if m != nil {
		return m.File
	}
	return ""
}

func (m *Meeting_Unknown) GetLog() string {
	if m != nil {
		return m.Log
	}
	return ""
}

type Meeting_Trace struct {
	Ip                   string   `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Meeting_Trace) Reset()         { *m = Meeting_Trace{} }
func (m *Meeting_Trace) String() string { return proto.CompactTextString(m) }
func (*Meeting_Trace) ProtoMessage()    {}
func (*Meeting_Trace) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c1c38a5767000fe, []int{0, 3}
}

func (m *Meeting_Trace) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Meeting_Trace.Unmarshal(m, b)
}
func (m *Meeting_Trace) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Meeting_Trace.Marshal(b, m, deterministic)
}
func (m *Meeting_Trace) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Meeting_Trace.Merge(m, src)
}
func (m *Meeting_Trace) XXX_Size() int {
	return xxx_messageInfo_Meeting_Trace.Size(m)
}
func (m *Meeting_Trace) XXX_DiscardUnknown() {
	xxx_messageInfo_Meeting_Trace.DiscardUnknown(m)
}

var xxx_messageInfo_Meeting_Trace proto.InternalMessageInfo

func (m *Meeting_Trace) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

type Meeting_Room struct {
	User                 string          `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	RoomName             string          `protobuf:"bytes,4,opt,name=room_name,json=roomName,proto3" json:"room_name,omitempty"`
	Connections          string          `protobuf:"bytes,10,opt,name=connections,proto3" json:"connections,omitempty"`
	Tunnels              string          `protobuf:"bytes,67,opt,name=tunnels,proto3" json:"tunnels,omitempty"`
	Handshake            string          `protobuf:"bytes,11,opt,name=handshake,proto3" json:"handshake,omitempty"`
	RoomId               uint32          `protobuf:"varint,12,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	PhoneNumbers         string          `protobuf:"bytes,17,opt,name=phone_numbers,json=phoneNumbers,proto3" json:"phone_numbers,omitempty"`
	JoinInfo             string          `protobuf:"bytes,25,opt,name=join_info,json=joinInfo,proto3" json:"join_info,omitempty"`
	GmailLink            string          `protobuf:"bytes,23,opt,name=gmail_link,json=gmailLink,proto3" json:"gmail_link,omitempty"`
	YahooLink            string          `protobuf:"bytes,24,opt,name=yahoo_link,json=yahooLink,proto3" json:"yahoo_link,omitempty"`
	Link                 string          `protobuf:"bytes,28,opt,name=link,proto3" json:"link,omitempty"`
	LinkWithToken        string          `protobuf:"bytes,44,opt,name=link_with_token,json=linkWithToken,proto3" json:"link_with_token,omitempty"`
	CallToAction         string          `protobuf:"bytes,46,opt,name=call_to_action,json=callToAction,proto3" json:"call_to_action,omitempty"`
	Phones               *Meeting_Phones `protobuf:"bytes,56,opt,name=phones,proto3" json:"phones,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Meeting_Room) Reset()         { *m = Meeting_Room{} }
func (m *Meeting_Room) String() string { return proto.CompactTextString(m) }
func (*Meeting_Room) ProtoMessage()    {}
func (*Meeting_Room) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c1c38a5767000fe, []int{0, 4}
}

func (m *Meeting_Room) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Meeting_Room.Unmarshal(m, b)
}
func (m *Meeting_Room) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Meeting_Room.Marshal(b, m, deterministic)
}
func (m *Meeting_Room) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Meeting_Room.Merge(m, src)
}
func (m *Meeting_Room) XXX_Size() int {
	return xxx_messageInfo_Meeting_Room.Size(m)
}
func (m *Meeting_Room) XXX_DiscardUnknown() {
	xxx_messageInfo_Meeting_Room.DiscardUnknown(m)
}

var xxx_messageInfo_Meeting_Room proto.InternalMessageInfo

func (m *Meeting_Room) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *Meeting_Room) GetRoomName() string {
	if m != nil {
		return m.RoomName
	}
	return ""
}

func (m *Meeting_Room) GetConnections() string {
	if m != nil {
		return m.Connections
	}
	return ""
}

func (m *Meeting_Room) GetTunnels() string {
	if m != nil {
		return m.Tunnels
	}
	return ""
}

func (m *Meeting_Room) GetHandshake() string {
	if m != nil {
		return m.Handshake
	}
	return ""
}

func (m *Meeting_Room) GetRoomId() uint32 {
	if m != nil {
		return m.RoomId
	}
	return 0
}

func (m *Meeting_Room) GetPhoneNumbers() string {
	if m != nil {
		return m.PhoneNumbers
	}
	return ""
}

func (m *Meeting_Room) GetJoinInfo() string {
	if m != nil {
		return m.JoinInfo
	}
	return ""
}

func (m *Meeting_Room) GetGmailLink() string {
	if m != nil {
		return m.GmailLink
	}
	return ""
}

func (m *Meeting_Room) GetYahooLink() string {
	if m != nil {
		return m.YahooLink
	}
	return ""
}

func (m *Meeting_Room) GetLink() string {
	if m != nil {
		return m.Link
	}
	return ""
}

func (m *Meeting_Room) GetLinkWithToken() string {
	if m != nil {
		return m.LinkWithToken
	}
	return ""
}

func (m *Meeting_Room) GetCallToAction() string {
	if m != nil {
		return m.CallToAction
	}
	return ""
}

func (m *Meeting_Room) GetPhones() *Meeting_Phones {
	if m != nil {
		return m.Phones
	}
	return nil
}

func init() {
	proto.RegisterType((*Meeting)(nil), "Meeting")
	proto.RegisterType((*Meeting_PhoneNumber)(nil), "Meeting.PhoneNumber")
	proto.RegisterType((*Meeting_Phones)(nil), "Meeting.Phones")
	proto.RegisterType((*Meeting_Unknown)(nil), "Meeting.Unknown")
	proto.RegisterType((*Meeting_Trace)(nil), "Meeting.Trace")
	proto.RegisterType((*Meeting_Room)(nil), "Meeting.Room")
}

func init() {
	proto.RegisterFile("meeting.proto", fileDescriptor_2c1c38a5767000fe)
}

var fileDescriptor_2c1c38a5767000fe = []byte{
	// 567 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x54, 0x93, 0x4f, 0x6f, 0xdb, 0x3c,
	0x0c, 0xc6, 0xd1, 0x26, 0x8d, 0x1b, 0xa6, 0x69, 0xfb, 0x0a, 0x2f, 0x56, 0x2d, 0xed, 0xb0, 0xec,
	0x5f, 0xd7, 0xc3, 0x10, 0x60, 0xd9, 0x65, 0xd7, 0xa1, 0xa7, 0x02, 0x5b, 0x51, 0x18, 0x19, 0x76,
	0x34, 0x5c, 0x47, 0x89, 0xb5, 0xd8, 0x92, 0x61, 0x39, 0x48, 0xfb, 0xb9, 0x86, 0x7d, 0x9d, 0x7d,
	0x96, 0x91, 0x94, 0x9c, 0x66, 0xa7, 0x90, 0xbf, 0x87, 0x91, 0xf8, 0x50, 0x34, 0x0c, 0x4b, 0xa5,
	0x1a, 0x6d, 0x96, 0x93, 0xaa, 0xb6, 0x8d, 0x7d, 0xfd, 0x27, 0x82, 0xe8, 0x9b, 0x27, 0x42, 0x42,
	0x54, 0x6a, 0xe7, 0x30, 0x94, 0x7b, 0xe3, 0xbd, 0xab, 0xc3, 0xb8, 0x4d, 0xc5, 0x18, 0x06, 0xda,
	0x2c, 0x6c, 0x5d, 0xa6, 0x8d, 0xb6, 0x46, 0xee, 0xa3, 0xda, 0x8f, 0x77, 0x91, 0x78, 0x05, 0xdd,
	0xda, 0xda, 0x52, 0x76, 0x50, 0x1a, 0x4c, 0x87, 0x93, 0x70, 0xe6, 0x24, 0x46, 0x18, 0xb3, 0x24,
	0xae, 0x20, 0xca, 0xd6, 0x75, 0xad, 0x4c, 0x23, 0x2f, 0xb9, 0xea, 0x78, 0x5b, 0x35, 0xab, 0xd3,
	0x4c, 0xc5, 0xad, 0x2c, 0x2e, 0xe1, 0x20, 0xb7, 0xae, 0x71, 0xf2, 0x7c, 0xdc, 0xc1, 0xba, 0xd3,
	0x6d, 0xdd, 0x77, 0xb3, 0x32, 0x76, 0x63, 0x62, 0x2f, 0x8f, 0x7e, 0xed, 0xc1, 0xe0, 0x2e, 0xb7,
	0x46, 0xdd, 0xae, 0xcb, 0x7b, 0x55, 0x63, 0x13, 0x47, 0x99, 0x5d, 0x9b, 0xa6, 0x7e, 0x4c, 0x32,
	0x3b, 0x57, 0xec, 0x02, 0xfb, 0x0c, 0xec, 0x1a, 0xd1, 0x6e, 0x89, 0x49, 0x4b, 0xd5, 0x5a, 0x09,
	0xec, 0x16, 0x91, 0x78, 0x07, 0xc7, 0x6d, 0x49, 0x55, 0xab, 0x85, 0x7e, 0x60, 0x53, 0xfd, 0x78,
	0x18, 0xe8, 0x1d, 0x43, 0xf1, 0x0c, 0x7a, 0x86, 0xaf, 0x95, 0x5d, 0x96, 0x43, 0x26, 0x5e, 0xc2,
	0x40, 0xa5, 0x0e, 0x8f, 0xf7, 0xe2, 0x01, 0x8b, 0x40, 0xc8, 0x77, 0x39, 0x9a, 0x42, 0x8f, 0x9b,
	0x76, 0x38, 0x91, 0x2e, 0xcd, 0x10, 0xfb, 0x24, 0x9b, 0xff, 0x6f, 0x6d, 0xee, 0x78, 0x8a, 0xb9,
	0x62, 0xb4, 0x84, 0x28, 0x78, 0x17, 0x02, 0xba, 0x0f, 0x65, 0x55, 0x05, 0x73, 0x1c, 0x8b, 0x53,
	0xe8, 0x2c, 0x37, 0x1f, 0x83, 0x19, 0x0a, 0x3d, 0x99, 0x86, 0xce, 0x29, 0xa4, 0xff, 0x2d, 0x74,
	0xa1, 0x42, 0xb7, 0x1c, 0x53, 0x55, 0x61, 0x97, 0xf2, 0xd0, 0x57, 0x61, 0x38, 0x3a, 0x83, 0x03,
	0x7e, 0x0c, 0x71, 0x0c, 0xfb, 0xba, 0xbd, 0x04, 0xa3, 0xd1, 0xef, 0x0e, 0x74, 0xe9, 0x31, 0xe9,
	0x9c, 0xb5, 0x43, 0x63, 0xfe, 0x68, 0x8e, 0xc5, 0x39, 0xf4, 0xe9, 0x89, 0xfd, 0x48, 0xfd, 0x05,
	0x87, 0x04, 0x78, 0x9e, 0xb8, 0x3c, 0x99, 0x35, 0x46, 0x65, 0xb4, 0x28, 0x4e, 0x42, 0x3b, 0xf1,
	0x2d, 0xa2, 0xc5, 0x6b, 0xd6, 0x98, 0x16, 0x4e, 0x5e, 0xb3, 0xda, 0xa6, 0xe2, 0x02, 0xfa, 0x79,
	0x6a, 0xe6, 0x2e, 0x4f, 0x57, 0x4a, 0x0e, 0x58, 0x7b, 0x02, 0xe2, 0x0c, 0x22, 0xbe, 0x56, 0xcf,
	0xe5, 0x11, 0x6a, 0xc3, 0xb8, 0x47, 0xe9, 0xcd, 0x5c, 0xbc, 0x81, 0x61, 0x45, 0x33, 0x0c, 0x8f,
	0xe0, 0xe4, 0x7f, 0xfc, 0xd7, 0xa3, 0xea, 0x69, 0xb0, 0x8e, 0x9a, 0xfe, 0x69, 0xb5, 0x49, 0xf8,
	0x09, 0x9e, 0xfb, 0xa6, 0x09, 0xdc, 0x60, 0x2e, 0x5e, 0x00, 0x2c, 0xcb, 0x54, 0x17, 0x49, 0xa1,
	0xcd, 0x4a, 0x9e, 0xf9, 0x9b, 0x99, 0x7c, 0x45, 0x40, 0xf2, 0x63, 0x9a, 0x5b, 0xeb, 0x65, 0xe9,
	0x65, 0x26, 0x2c, 0xe3, 0x8c, 0x58, 0xb8, 0xf0, 0x33, 0xa2, 0x18, 0x97, 0xfa, 0x84, 0x7e, 0x93,
	0x8d, 0x6e, 0xf2, 0xa4, 0xb1, 0x2b, 0x65, 0xe4, 0x07, 0xbf, 0x57, 0x84, 0x7f, 0x20, 0x9d, 0x11,
	0x14, 0x6f, 0x71, 0xfd, 0xd2, 0xa2, 0xc0, 0x92, 0x24, 0xe5, 0xf9, 0xc8, 0x89, 0x6f, 0x9e, 0xe8,
	0xcc, 0x7e, 0x61, 0x26, 0xde, 0x43, 0x8f, 0xcd, 0x38, 0xf9, 0x99, 0xbf, 0xa5, 0x93, 0x7f, 0x97,
	0xc7, 0xc5, 0x41, 0xbe, 0xef, 0xf1, 0x77, 0xfe, 0xe9, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x76,
	0x05, 0x89, 0x93, 0xf8, 0x03, 0x00, 0x00,
}
